### ISSUE TITLE
drone社区版已经有各种限制了，还继续推荐使用吗？

### ISSUE THREAD

**Issue by pc10201** [appleboy/drone-lambda#8]
drone社区版已经有各种限制了，还继续推荐使用吗？

详细链接 https://docs.drone.io/enterprise/

**Comment by appleboy** [comment]
當然推薦使用啊，有什麼限制嗎？

> Yes. The Enterprise Edition includes a free trial for up to 5000 builds. You can download and use the Enterprise Edition by following the installation instructions described in this documentation.

**Comment by pc10201** [comment]
社区版不支持mysql，只支持sqlite，也不支持插件
